services:
  nginx:
    container_name: test_task_nginx
    build: ./nginx
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - app
    networks:
      - app-network

  app:
    container_name: test_task_app
    build: .
    restart: on-failure
    depends_on:
      - db
      - minio
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - ./alembic/versions:/src/alembic/versions

  db:
    container_name: test_task_db
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - app-network

  minio:
    container_name: test_task_minio
    image: minio/minio
    volumes:
      - ./media_minio:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    networks:
      - app-network


networks:
  app-network:
volumes:
  app:
    driver: local
  db:
    driver: local
  minion:
    driver: local