FROM python:3.10

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./src /src
COPY ./tests /tests

WORKDIR /tests

USER root:root

CMD ["pytest", "-s", "-c", "pytest.ini"]