"""change payment type to enum

Revision ID: 943986d1edc1
Revises: 2082de609f2b
Create Date: 2025-01-09 15:29:14.458748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943986d1edc1'
down_revision: Union[str, None] = '2082de609f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('cash', 'card', name='paymenttypeenum').create(op.get_bind())
    op.alter_column('tickets', 'payment_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('cash', 'card', name='paymenttypeenum'),
               nullable=True,
               postgresql_using='payment_type::paymenttypeenum')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'payment_type',
               existing_type=sa.Enum('cash', 'card', name='paymenttypeenum'),
               type_=sa.VARCHAR(),
               nullable=False)
    sa.Enum('cash', 'card', name='paymenttypeenum').drop(op.get_bind())
    # ### end Alembic commands ###
